let questionStore = [
  [
    {
      answer: 'F',
      stem: '床前明月光，疑是地__霜',
      options: [
        { content: '巩', option: 'A' },
        { content: '镣', option: 'B' },
        { content: '茶', option: 'C' },
        { content: '棠', option: 'D' },
        { content: '帝', option: 'E' },
        { content: '上', option: 'F' },
        { content: '蒋', option: 'G' },
        { content: '症', option: 'H' },
      ],
      img: null,
      no: 1,
    },
    {
      answer: 'G',
      stem: '鹅，鹅，鹅，曲项向__歌',
      options: [
        { content: '痉', option: 'A' },
        { content: '慎', option: 'B' },
        { content: '喉', option: 'C' },
        { content: '吏', option: 'D' },
        { content: '枷', option: 'E' },
        { content: '厕', option: 'F' },
        { content: '天', option: 'G' },
        { content: '咕', option: 'H' },
      ],
      img: null,
      no: 2,
    },
    {
      answer: 'C',
      stem: '一去二三里，烟村四五__',
      options: [
        { content: '莉', option: 'A' },
        { content: '填', option: 'B' },
        { content: '家', option: 'C' },
        { content: '锤', option: 'D' },
        { content: '洪', option: 'E' },
        { content: '概', option: 'F' },
        { content: '墩', option: 'G' },
        { content: '椎', option: 'H' },
      ],
      img: null,
      no: 3,
    },
    {
      answer: 'D',
      stem: '春__不觉晓，处处闻啼鸟',
      options: [
        { content: '困', option: 'A' },
        { content: '怒', option: 'B' },
        { content: '恍', option: 'C' },
        { content: '眠', option: 'D' },
        { content: '色', option: 'E' },
        { content: '花', option: 'F' },
        { content: '雀', option: 'G' },
        { content: '巷', option: 'H' },
      ],
      img: null,
      no: 4,
    },
    {
      answer: 'F',
      stem: '夜来风__声，花落知多少',
      options: [
        { content: '渐', option: 'A' },
        { content: '云', option: 'B' },
        { content: '沙', option: 'C' },
        { content: '柿', option: 'D' },
        { content: '洪', option: 'E' },
        { content: '雨', option: 'F' },
        { content: '咳', option: 'G' },
        { content: '恻', option: 'H' },
      ],
      img: null,
      no: 5,
    },
  ],
  [
    {
      answer: 'E',
      stem: '小__才露尖尖角，早有蜻蜓立上头',
      options: [
        { content: '骤', option: 'A' },
        { content: '白', option: 'B' },
        { content: '沃', option: 'C' },
        { content: '许', option: 'D' },
        { content: '荷', option: 'E' },
        { content: '弊', option: 'F' },
        { content: '丹', option: 'G' },
        { content: '秽', option: 'H' },
      ],
      img: null,
      no: 1,
    },
    {
      answer: 'H',
      stem: '离离__上草，一岁一枯荣',
      options: [
        { content: '唁', option: 'A' },
        { content: '斤', option: 'B' },
        { content: '待', option: 'C' },
        { content: '悄', option: 'D' },
        { content: '屎', option: 'E' },
        { content: '比', option: 'F' },
        { content: '褪', option: 'G' },
        { content: '原', option: 'H' },
      ],
      img: null,
      no: 2,
    },
    {
      answer: 'B',
      stem: '日照香炉生紫烟，遥__瀑布挂前川',
      options: [
        { content: '编', option: 'A' },
        { content: '看', option: 'B' },
        { content: '帆', option: 'C' },
        { content: '披', option: 'D' },
        { content: '唬', option: 'E' },
        { content: '绽', option: 'F' },
        { content: '嗅', option: 'G' },
        { content: '怔', option: 'H' },
      ],
      img: null,
      no: 3,
    },
    {
      answer: 'D',
      stem: '白日依山尽，黄河入海__',
      options: [
        { content: '滩', option: 'A' },
        { content: '岸', option: 'B' },
        { content: '滨', option: 'C' },
        { content: '流', option: 'D' },
        { content: '宫', option: 'E' },
        { content: '沙', option: 'F' },
        { content: '龙', option: 'G' },
        { content: '吏', option: 'H' },
      ],
      img: null,
      no: 4,
    },
    {
      answer: 'C',
      stem: '两个黄鹂鸣翠柳，一行__鹭上青天',
      options: [
        { content: '昂', option: 'A' },
        { content: '帅', option: 'B' },
        { content: '白', option: 'C' },
        { content: '红', option: 'D' },
        { content: '青', option: 'E' },
        { content: '小', option: 'F' },
        { content: '幼', option: 'G' },
        { content: '老', option: 'H' },
      ],
      img: null,
      no: 5,
    },
  ],
  [
    {
      answer: 'G',
      stem: '__花香里说丰年，听取蛙声一片',
      options: [
        { content: '梅', option: 'A' },
        { content: '梨', option: 'B' },
        { content: '菊', option: 'C' },
        { content: '各', option: 'D' },
        { content: '较', option: 'E' },
        { content: '妒', option: 'F' },
        { content: '稻', option: 'G' },
        { content: '序', option: 'H' },
      ],
      img: null,
      no: 1,
    },
    {
      answer: 'F',
      stem: '欲穷千里目，更__一层楼',
      options: [
        { content: '爬', option: 'A' },
        { content: '踏', option: 'B' },
        { content: '攀', option: 'C' },
        { content: '进', option: 'D' },
        { content: '招', option: 'E' },
        { content: '上', option: 'F' },
        { content: '迈', option: 'G' },
        { content: '招', option: 'H' },
      ],
      img: null,
      no: 2,
    },
    {
      answer: 'H',
      stem: '__头望明月，低头思故乡',
      options: [
        { content: '抬', option: 'A' },
        { content: '仰', option: 'B' },
        { content: '低', option: 'C' },
        { content: '伸', option: 'D' },
        { content: '探', option: 'E' },
        { content: '摸', option: 'F' },
        { content: '挠', option: 'G' },
        { content: '举', option: 'H' },
      ],
      img: null,
      no: 3,
    },
    {
      answer: 'F',
      stem: '谁言__草心，报得三春晖',
      options: [
        { content: '野', option: 'A' },
        { content: '潦', option: 'B' },
        { content: '花', option: 'C' },
        { content: '小', option: 'D' },
        { content: '芥', option: 'E' },
        { content: '寸', option: 'F' },
        { content: '老', option: 'G' },
        { content: '汀', option: 'H' },
      ],
      img: null,
      no: 4,
    },
    {
      answer: 'F',
      stem: '__识庐山真面目，只缘身在此山中',
      options: [
        { content: '才', option: 'A' },
        { content: '刚', option: 'B' },
        { content: '一', option: 'C' },
        { content: '认', option: 'D' },
        { content: '有', option: 'E' },
        { content: '不', option: 'F' },
        { content: '由', option: 'G' },
        { content: '犹', option: 'H' },
      ],
      img: null,
      no: 5,
    },
  ],
];

export default questionStore;
